In [15]:
import torch

In [19]:
# Создайте случайный FloatTensor размера 3x4x5

torch.FloatTensor()
a = torch.Tensor()
print(a)

# Создал пустой тензор и посмотред работает ли торч.

tensor([])


In [34]:
# На сколько я понял то создать случайный Float можно так: 

a = torch.randn(3, 4, 5).type(torch.FloatTensor)

print(a)

# Прошу не судить строго

tensor([[[ 0.7406,  0.1573, -1.2021,  0.5245, -0.5503],
         [-0.1321, -0.8306,  0.6281, -0.0743,  0.1800],
         [ 0.0080, -0.1306, -0.7560, -0.0096, -0.8766],
         [-1.5292, -0.0454,  0.6456, -1.2675, -0.0064]],

        [[ 2.1672, -0.8868,  0.4271, -1.5739,  0.9437],
         [-1.1918, -1.3313,  0.0928,  0.2759,  1.1963],
         [-1.0177,  2.0010, -0.9498,  0.7940, -0.2483],
         [-0.1429,  0.7537, -3.1043, -0.2495,  0.1051]],

        [[ 2.0389, -0.4655, -1.8727, -0.2467, -0.8174],
         [ 0.2732, -0.0094, -0.1650,  1.1498,  0.6477],
         [ 1.0789, -1.9159,  0.2071,  0.3405,  1.0108],
         [ 0.2664,  0.3342,  0.5341,  0.8369, -1.0792]]])


In [35]:
# Выведите его форму (shape)
# Не знаю что у меня получилось но что получилось то и получилось ))

print(f"a: {a}\nshape: {a.size()}")

# В итоге у нас получился shape ([3, 4, 5])

a: tensor([[[ 0.7406,  0.1573, -1.2021,  0.5245, -0.5503],
         [-0.1321, -0.8306,  0.6281, -0.0743,  0.1800],
         [ 0.0080, -0.1306, -0.7560, -0.0096, -0.8766],
         [-1.5292, -0.0454,  0.6456, -1.2675, -0.0064]],

        [[ 2.1672, -0.8868,  0.4271, -1.5739,  0.9437],
         [-1.1918, -1.3313,  0.0928,  0.2759,  1.1963],
         [-1.0177,  2.0010, -0.9498,  0.7940, -0.2483],
         [-0.1429,  0.7537, -3.1043, -0.2495,  0.1051]],

        [[ 2.0389, -0.4655, -1.8727, -0.2467, -0.8174],
         [ 0.2732, -0.0094, -0.1650,  1.1498,  0.6477],
         [ 1.0789, -1.9159,  0.2071,  0.3405,  1.0108],
         [ 0.2664,  0.3342,  0.5341,  0.8369, -1.0792]]])
shape: torch.Size([3, 4, 5])


In [37]:
# Приведите его к форме 6 X 10

a = torch.FloatTensor(6 * 10)
print(a)

tensor([ 0.7406,  0.1573, -1.2021,  0.5245, -0.5503, -0.1321, -0.8306,  0.6281,
        -0.0743,  0.1800,  0.0080, -0.1306, -0.7560, -0.0096, -0.8766, -1.5292,
        -0.0454,  0.6456, -1.2675, -0.0064,  2.1672, -0.8868,  0.4271, -1.5739,
         0.9437, -1.1918, -1.3313,  0.0928,  0.2759,  1.1963, -1.0177,  2.0010,
        -0.9498,  0.7940, -0.2483, -0.1429,  0.7537, -3.1043, -0.2495,  0.1051,
         2.0389, -0.4655, -1.8727, -0.2467, -0.8174,  0.2732, -0.0094, -0.1650,
         1.1498,  0.6477,  1.0789, -1.9159,  0.2071,  0.3405,  1.0108,  0.2664,
         0.3342,  0.5341,  0.8369, -1.0792])


In [40]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
# Я не смог найти прикрепленную методичку к уроку и не совсем понял как это делать.
b = torch.randn(1, 4, 3).type(torch.FloatTensor)
print(f"a + b: {a + b},\n a * b: {a * b}")

Unexpected exception formatting exception. Falling back to standard exception


Traceback (most recent call last):
  File "c:\Users\azhur\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\azhur\AppData\Local\Temp\ipykernel_19184\3873683434.py", line 4, in <cell line: 4>
    print(f"a + b: {a + b},\n a * b: {a * b}")
RuntimeError: The size of tensor a (60) must match the size of tensor b (3) at non-singleton dimension 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\azhur\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\interactiveshell.py", line 1993, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "c:\Users\azhur\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\ultratb.py", line 1118, in structured_traceback
    return FormattedTB.structured_traceback(
  File "c:\Users\azhur\AppData\Lo

In [6]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6

In [7]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [44]:
# Создайте единичный тензор размера 5x6

a = torch.Tensor(5, 6)
a

tensor([[6.7747e+31, 6.2638e-43, 1.4013e-45, 0.0000e+00, 2.8026e-45, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 1.4013e-45, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 2.8026e-45, 0.0000e+00, 9.1841e-41, 1.1551e-40]])

In [9]:
# Переведите его в формат numpy

In [ ]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 